import { CSSObject } from 'styled-components'

import type { CreateThemeVarsOptions, ThemeVars } from './create'

const themeVarDefaultFunction = (): CSSObject => ({})

export const createThemeVars = (
    options = {} as CreateThemeVarsOptions
): ThemeVars => {
    const {
        button = themeVarDefaultFunction,
        buttonBase = themeVarDefaultFunction,
        iconButton = themeVarDefaultFunction,
        buttonGroup = themeVarDefaultFunction,
        inputBase = themeVarDefaultFunction,
        input = themeVarDefaultFunction,
        box = themeVarDefaultFunction,
        grid = themeVarDefaultFunction,
        gridItem = themeVarDefaultFunction,
        spinner = themeVarDefaultFunction,
        typography = themeVarDefaultFunction,
        label = themeVarDefaultFunction,
        checkbox = themeVarDefaultFunction,
        radio = themeVarDefaultFunction,
        radioGroup = themeVarDefaultFunction,
        formControlLabel = themeVarDefaultFunction,
        toggle = themeVarDefaultFunction,
        divider = themeVarDefaultFunction,
        collapsible = themeVarDefaultFunction,
        list = themeVarDefaultFunction,
        listItem = themeVarDefaultFunction,
        listHeading = themeVarDefaultFunction,
        alert = themeVarDefaultFunction,
        alertGroup = themeVarDefaultFunction,
        inlineAlert = themeVarDefaultFunction,
        card = themeVarDefaultFunction,
        cardAction = themeVarDefaultFunction,
        cardHeader = themeVarDefaultFunction,
        cardContent = themeVarDefaultFunction,
        tooltip = themeVarDefaultFunction,
        popper = themeVarDefaultFunction,
        menu = themeVarDefaultFunction,
        menuHeading = themeVarDefaultFunction,
        menuItem = themeVarDefaultFunction,
        stepper = themeVarDefaultFunction,
        table = themeVarDefaultFunction,
        tableBody = themeVarDefaultFunction,
        tableCell = themeVarDefaultFunction,
        tableHead = themeVarDefaultFunction,
        tableRow = themeVarDefaultFunction,
        modal = themeVarDefaultFunction,
    } = options

    return {
        button,
        buttonBase,
        iconButton,
        buttonGroup,
        inputBase,
        input,
        box,
        grid,
        gridItem,
        spinner,
        typography,
        label,
        checkbox,
        radio,
        radioGroup,
        formControlLabel,
        toggle,
        divider,
        collapsible,
        list,
        listItem,
        listHeading,
        alert,
        alertGroup,
        inlineAlert,
        card,
        cardAction,
        cardContent,
        cardHeader,
        tooltip,
        popper,
        menu,
        menuHeading,
        menuItem,
        stepper,
        table,
        tableBody,
        tableCell,
        tableHead,
        tableRow,
        modal,
    }
}
