name: publish

on:
    push:
        branches:
            - production

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm install
            - run: npm install -g npm-install-peers
            - run: npm-install-peers
            - run: npm run prod
            - run: cp package.json README.md LICENSE dist
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
